### PR TITLE
uri_escape the URL query string or the request won't sign correctly

### PR DESCRIPTION
**Pull request by vinhboy**
Fix issue #1 - properly sign requests where the URL has spaces or `+` symbols in the query string.

### CODE REVIEW

**Comment by winebarrel** [comment]
Thanks!

**Comment by winebarrel** [comment]
v0.1.3 has been released! Please try it out!

**Comment by vinhboy** [comment]
Sorry, I just realized that my fix does not work. We can't use `Seahorse::Util.uri_escape` on `url.query` because the query is already escaped.

So a string like `q=product` would be escaped to `q%3Dproduct`, which is not what we want.

I also reviewed your latest commits and you are only escaping for spaces, but it's not just spaces, it's also the `+` (plus) symbols.

AWS does not properly encode the `+` symbols, they expect it to be `%20`.

I will try to write a test to fix this.

**Comment by winebarrel** [comment]
OK,

I has been fix it.
Please try v0.1.4.

**Comment by vinhboy** [comment]
Ok. It's fixed. Thanks.

**Comment by winebarrel** [comment]
:smile:

**Comment by hrishikesh** [comment]
@winebarrel : iam still facing same issue with latest version

**Pull request merged**
